[[caddy-docker-images]]
= Caddy Docker images

image:https://travis-ci.org/openshift-s2i/s2i-caddy.svg?branch=master["Build Status", link="https://travis-ci.org/openshift-s2i/s2i-caddy"]

This repository contains the source for creating a
https://github.com/openshift/source-to-image[source-to-image] builder image,
which be used to create reproducible Docker images from your web project's
source code.  The resulting image can be run using https://docker.com[Docker].

For more information about using these images with OpenShift, please see
the official
https://docs.openshift.org/latest/using_images/s2i_images/php.html[OpenShift
Documentation].

[[versions]]
== Versions

Caddy versions currently supported are:

* Caddy 0.8.2

The following operating system base images are supported:

* CentOS 7

[[installation]]
== Installation

To build a Caddy builder image, execute:

----------------------------------------------------------
$ git clone https://github.com/openshift-s2i/s2i-caddy.git
$ cd s2i-caddy
$ make build VERSION=0.8
----------------------------------------------------------

Alternatively, you can pull the CentOS image from Docker Hub via:

----------------------------------------
$ docker pull openshift/caddy-08-centos7
----------------------------------------

*Notice: By omitting the `VERSION` parameter, the build/test action will
be performed on all the supported versions of Caddy.*

[[usage]]
== Usage

There are sample web sites included with this repository.  To serve the sample
web site using Caddy, run the s2i build:

---------------------------------------------------------------------------------
$ s2i build https://github.com/openshift-s2i/s2i-caddy.git \
    --context-dir=0.8/test/test-app openshift/caddy-08-centos7 caddy-test-app
---------------------------------------------------------------------------------

The resulting image can be executed using https://docker.com[docker]:

-------------------------------------------------------
$ docker run --rm -p 8080:80 -p 8443:443 caddy-test-app
-------------------------------------------------------

Once the container is running, it should be accessible using:

---------------------
$ curl 127.0.0.1:8080
---------------------

[[test]]
== Test

This repository also provides a test suite to check functionality of simple
Caddy web sites or applications built on top of the `s2i-caddy` image.  It
can be executed simply by running the `make test` command:

-----------------------
$ cd s2i-caddy
$ make test VERSION=0.8
-----------------------

*Notice: By omitting the `VERSION` parameter, the build/test action will
be performed on all the supported versions of Caddy.*

[[repository-organization]]
Repository organization
~~~~~~~~~~~~~~~~~~~~~~~

* *`<caddy-version>`*: Dockerfile to build container images from.

** *`<caddy-version>/test/test-app`*: Sample Caddy web site used for tests.

* *`hack/`*: Folder containing scripts which are responsible for the build
and test actions performed by the `Makefile`.

* *`s2i/`*: Build scripts which will be injected into the builder image
and executed during application source code builds.

[[image-name-structure]]
Image name structure
~~~~~~~~~~~~~~~~~~~~

[[structure-openshift1-2-3]]
Structure: openshift/1-2-3

1.  Platform name (lowercase) - caddy
2.  Platform version(without dots) - 08
3.  Base builder image - centos7

Examples: `openshift/caddy-08-centos7`

[[contributing]]
Contributing
~~~~~~~~~~~~

Contributions to this project (in the form of bug reports, patches, or pull
requests) are gratefully accepted by the maintainer.  Please see the
link:Contributing.adoc[Contributing.adoc] file contained in this package
for details.

[[copyright-license]]
Copyright and License
~~~~~~~~~~~~~~~~~~~~~

Copyright 2016 by Red Hat, Inc.

Licensed under the Apache License, Version 2.0 (the "License"); you may not
use this package except in compliance with the License (see the `LICENSE` file
included in this distribution). You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
License for the specific language governing permissions and limitations under
the License.
